version: "3.7"
services:
    # image project
    me2-lumen-app:
        build:
            args:
                user: me2user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: lumen-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - me2-lumen-network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8081:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - me2-lumen-network

    # db mysql
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - me2-lumen-network

networks:
    me2-lumen-network:
        driver: bridge
